

pub enum Target {
    Byte(u8),
    Short(u8),
    Integer(u8),
    Long(u8),
    Float(u8),
    Double(u8),
    Zero,
    Seed,
    IntExn,
    FloatExn,
    Trap,
    TrapCause,
    TrapVal,
    Inter,
}

pub enum Bytecode {
    LoadImmediate8(u8),
    LoadImmediate16(u16),
    LoadImmediate32(u32),
    LoadImmediate64(u64),
    LoadRegister(Target, Target),
    LoadAddress(Target, Target),
    StoreRegister64(Target, Target),
    AddSigned(Target, Target, Target),
    AddUnsigned(Target, Target, Target),
    SubSigned(Target, Target, Target),
    SubUnsigned(Target, Target, Target),
    MulSigned(Target, Target, Target),
    MulUnsigned(Target, Target, Target),
    DivSigned(Target, Target, Target, Target),
    DivUnsigned(Target, Target, Target, Target),
    AddFloat(Target, Target, Target),
    SubFloat(Target, Target, Target),
    MulFloat(Target, Target, Target),
    DivFloat(Target, Target, Target),
    Sqrt(Target, Target, Target),
    ConvertFloatInt(Target, Target),
    ConvertIntFloat(Target, Target),
    Or(Target, Target, Target),
    And(Target, Target, Target),
    Xor(Target, Target, Target),
    Complement(Target, Target),
    ShiftRightArithmetic(Target, Target),
    ShiftRightLogical(Target, Target),
    ShiftLeftArithmetic(Target, Target),
    ShiftLeftLogical(Target, Target),
    RotateRight(Target, Target),
    RotateLeft(Target, Target),
    Equal(Target, Target, Target),
    LessThanSigned(Target, Target, Target),
    LessThanUnsigned(Target, Target, Target),
    GreaterThanSigned(Target, Target, Target),
    GreaterThanUnsigned(Target, Target, Target),
    LessThanEqualSigned(Target, Target, Target),
    LessThanEqualUnsigned(Target, Target, Target),
    GreaterThanEqualSigned(Target, Target, Target),
    GreaterThanEqualUnsigned(Target, Target, Target),
    EqualFloat(Target, Target, Target),
    LessThanFloat(Target, Target, Target),
    GreaterThanFloat(Target, Target, Target),
    LessThanEqualFloat(Target, Target, Target),
    GreaterThanEqualFloat(Target, Target, Target),
    JumpOffset16(Target, Target),
    JumpTo(Target, Target),
    BranchEq(Target, Target, Target),
    BranchNe(Target, Target, Target),
    BranchLts(Target, Target, Target),
    BranchLtu(Target, Target, Target),
    BranchGts(Target, Target, Target),
    BranchGtu(Target, Target, Target),
    BranchLes(Target, Target, Target),
    BranchLeu(Target, Target, Target),
    BranchGes(Target, Target, Target),
    BranchGeu(Target, Target, Target),
    CardCount(Target),
    CardName(Target, Target),
    CardCall,
}